function createfigure(X1, Y1, X2, Y2, Y3, Y4, Y5, X3, Y6, C1)
%CREATEFIGURE(X1,Y1,X2,Y2,Y3,Y4,Y5,X3,Y6)
%  X1:  vector of x data - time
%  Y1:  vector of y data - raw ecg
%  X2:  vector of x data - freq
%  Y2:  vector of y data - Raw ecg FT
%  Y3:  vector of y data - Filt ECG
%  Y4:  vector of y data  - Filt ECG FT
%  Y5:  vector of y data - Filt EMG
%  X3:  vector of x data - Freq
%  Y6:  vector of y data - Filt EMG FT

%  Auto-generated by MATLAB on 07-May-2009 06:49:33

% Create figure
figure1 = figure('PaperSize',[20.98 29.68]);

% Create subplot
subplot1 = subplot(3,2,1,'Parent',figure1);
box('on');
hold('all');

% Create plot
plot(X1,Y1,'Parent',subplot1);

% Create title
title('ECG');

% Create subplot
subplot2 = subplot(3,2,2,'Parent',figure1);
box('on');
hold('all');

% Create plot
plot(X2,Y2,'Parent',subplot2);

% Create subplot
subplot3 = subplot(3,2,3,'Parent',figure1);
box('on');
hold('all');

% Create plot
plot(X1,Y3,'Parent',subplot3);

% Create title
title('Filtered ECG');

% Create subplot
subplot4 = subplot(3,2,4,'Parent',figure1);
box('on');
hold('all');

% Create plot
plot(X2,Y4,'Parent',subplot4);

% Create subplot
subplot5 = subplot(3,2,5,'Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([0 30]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([-5 5]);
box('on');
grid('on');
hold('all');

% Create plot
plot(X1,Y5,'Parent',subplot5);

% Create title
title('Filtered EMG');

% Create xlabel
xlabel('Secs');

% Create ylabel
ylabel('EMG  (mVolts)');

% Create subplot
subplot6 = subplot(3,2,6,'Parent',figure1);
box('on');
hold('all');

% Create plot
plot(X3,Y6,'Parent',subplot6);

% Create title
title('Single-Sided Amplitude Spectrum of y(t)');

% Create xlabel
xlabel('Frequency (Hz)');

% Create ylabel
ylabel('|Y(f)|');

% Create textbox
HeartRate = 22;
annotation(figure1,'textbox',[0.926 0.795 0.07692 0.05545],'String',{'HR=' C1});

